//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocateGood
    {

        public int Id { get; set; }
        public Nullable<System.DateTime> DateOfAllocatioN { get; set; }
        public Nullable<int> NumOfItems { get; set; }
        public Nullable<int> DisasterId { get; set; }
        public Nullable<int> GoodId { get; set; }

        public virtual Disaster GetDisaster { get; set; }
        public virtual GoodDonation GoodDonation { get; set; }
    }
}
