//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocateMoney
    {
        public int Id { get; set; }
        public System.DateTime AllocationDate { get; set; }
        public Nullable<decimal> ALloocationAmount { get; set; }
        public Nullable<int> DisasterId { get; set; }

        public virtual Disaster Disaster { get; set; }
    }
}
